add Juho's topic
YGLF-Kyiv/website-2018 pull request #45
Opened 2018-04-06 15:49 UTC by salivan

2018-04-06 15:55 UTC, tyv commented on data/schedule.js
> +          "className": "juho-vepsalainen",
think it should be empty, denis was special and has special css

2018-04-06 15:55 UTC, tyv requested changes
remove className

2018-04-06 18:06 UTC, marina-marina commented on data/schedule.js
> +          "Organizing a conference means you require a certain amount of technical infrastructure. We developed a custom website and application for <a target=\"_blank\" href='https://react-finland.f
plz add 2 more spaces here

2018-04-10 11:18 UTC, marina-marina commented
https://github.com/YGLF-Kyiv/website-2018/pull/46

2018-04-10 11:18 UTC, closed without merging